version: '3'

services:
  web: &web
    build:
      context: ../
      dockerfile: ".build/Dockerfile"
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/project
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST_AUTH_METHOD=password
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    <<: *web
    image: web-celery
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ..:/project:z
    ports: [ ]
    command: celery -A toDoApp.celery worker --beat --loglevel=info

volumes:
  postgres_data:
