version: '3'

services:
  web: &web
    build:
      context: ../
      dockerfile: ".build/Dockerfile"
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/project
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DJANGO_MAIN_APP=toDoApp
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST_AUTH_METHOD=password

  database:
    image: postgres:latest
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"

volumes:
  postgres_data:
